const mongoose = require('mongoose'); 
const Schema = mongoose.Schema;
const Story = new Schema({
    title: { type: String,},
    author:{type:String},
    category: { type: String,},
    date: {type:Date},
    images:{type: String},
    sumary:{type:String},
    content:{type:String},

    title1: { type: String},
    title2: { type: String},
    title3: { type: String,},
    // title4: { type: String,},
    // title5: { type: String,},
    // title6: { type: String,},
    // title7: { type: String,},
    // title8: { type: String,},
    // title9: { type: String,},
    // title10: { type: String,},
    // title11: { type: String,},
    // title12: { type: String,},
    // title13: { type: String,},
    // title14: { type: String,},
    // title15: { type: String,},
    // title16: { type: String,},
    // title17: { type: String,},
    // title18: { type: String,},
    // title19: { type: String,},
    // title20: { type: String,},
    // title21: { type: String,},
    // title22: { type: String,},
    // title23: { type: String,},
    // title24: { type: String,},
    // title25: { type: String,},
    // title26: { type: String,},
    // title27: { type: String,},
    // title28: { type: String,},
    // title29: { type: String,},
    // title30: { type: String,},

    images1:{type: String},
    images2:{type: String},
    images3:{type: String},
    // images4:{type: String},
    // images5:{type: String},
    // images6:{type: String},
    // images7:{type: String},
    // images8:{type: String},
    // images9:{type: String},
    // images10:{type: String},
    // images11:{type: String},
    // images12:{type: String},
    // images13:{type: String},
    // images14:{type: String},
    // images15:{type: String},
    // images16:{type: String},
    // images17:{type: String},
    // images18:{type: String},
    // images19:{type: String},
    // images20:{type: String},
    // images21:{type: String},
    // images22:{type: String},
    // images23:{type: String},
    // images24:{type: String},
    // images25:{type: String},
    // images26:{type: String},
    // images27:{type: String},
    // images28:{type: String},
    // images29:{type: String},
    // images30:{type: String},
    createdAt:{type:Date, default: Date.now},
    updatedAt:{type:Date, default: Date.now},
  });
module.exports =mongoose.model('Story', Story); 